services:
  - type: web
    name: mental-clinic-backend
    env: node
    rootDir: apps/backend
    buildCommand: corepack enable && pnpm install --frozen-lockfile --prod
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false

  - type: web
    name: mental-clinic-fe
    env: node
    rootDir: apps/frontend
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm run serve:ssr:mentalClinicFe
